### ISSUE TITLE
Unable to import components in Typescript

### ISSUE THREAD

**Issue by jvanharn** [basvandenberg/ng-select#118]
Because not all files/components are exported in the index file, type-completion/type-checking cannot occur when you want a direct reference to the select component.

## Problem:
```typescript
import { SelectComponent } from 'angular2-select';
```
Will therefore not work. One of the sub-paths also fails to include (e.g. 'angular2-select/dist/select.component').

## Fix:
Export the components in your index.ts file, that way I will be able to actually access your component's public API in a type-safe way.

If you would like a pull request instead of just a bug, please let me know and I will create on at my earliest convenience.

**Comment by Crevil** [comment]
@basvandenberg The commit [687f7aa067bba000a2498842dcc3582b00698b25](https://github.com/basvandenberg/ng-select/commit/687f7aa067bba000a2498842dcc3582b00698b25) takes is some of the way.

It would be great if you exported a type for the options as well. By adding an interface like below to [`SelectComponent:L26`](https://github.com/basvandenberg/ng-select/blob/beta.4/src/select.component.ts#L26) instead of `any` you would enable users to have type safety for the options passed to the component.

```typescript
export interface ISelectOption {
  value: string;
  label: string;
}
```
The interface is based on the comment in the readme specifying what properties should be available.

Generally all the places where you know the type, it would be great if this was used. On the top of my head, that includes the `selected` and `deselected` events as well.

**Comment by basvandenberg** [comment]
In the `1.0.0-beta.4` release you should be able to import SelectComponent and the new IOption interface. Please let me know if there are any issues with this, then I'll reopen the issue.
