### ISSUE TITLE
ng-select not working with angular4.0.0

### ISSUE THREAD

**Issue by willidad** [basvandenberg/ng-select#143]
After upgrading to angular 4.0.0 I am getting  
'Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '1'. Current value: '111'.

ng-select worked prefectly with Angular 2.1.x. 

I have been able to reproduce this error with an simple example. The template and the component code are attached, the rest is the code generated by angular cli.

The problem goes away if I remove the placeholder property from <ng-select ...>

Template: 
```html
<ng-select
    [options]="options"
    [multiple]="true"
    placeholder="placeholder"
    [(ngModel)]="values">
</ng-select>
```
Typescript code:
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  options: Array<any>;
  values: string[];

  ngOnInit() {
    this.options = [];
    for (let i = 0; i < 15; i++) {
      this.options.push({ value: i.toString(), label: 'l' + i });
    }
    this.values = ['1', '2'];
  }

  selected() {
    console.log('selected')
  }

  deselected() {
    console.log('deselected')
  }
}
```

**Comment by PMJMendes** [comment]
It looks like this bug crawled back into existence in beta 6. The problem is that ngStyle is changing during afterViewInit, because of the call to updateState. The culprit seems to be [this commit](https://github.com/basvandenberg/ng-select/commit/52cfa1cab77986f4ba68e5d5d102763b900d9c8b). I would suggest wrapping the ngAfterViewInit call to updateState in a setTimeout.

**Comment by aniruddhadas9** [comment]
I am facing the same issue in `1.0.0-beta.6`
