### ISSUE TITLE
Set a default selected value dynamiccaly

### ISSUE THREAD

**Issue by meiuqer** [basvandenberg/ng-select#151]
Hi, I'm working on a text editor and i'm using multiple text items with multiple ng-selects for selecting a font.

When i save my project and refresh i want the font to appear in the ng-select input. But every item can have different fonts. So they need to be called dynamically. I'm using the ngModel example which is working fine for saving it but not for loading it in the ng-select.

Am i missing something or is this not possible?

**Comment by basvandenberg** [comment]
`ngModel` can be used both for getting and setting the `ng-select` value.

If you are sure that this is a `ng-select` issue, please provide a simple code example/plunkr to illustrate the issue. Otherwise, if you need help getting the component to work, please ask a question on stackoverflow or something similar.
