### ISSUE TITLE
No filter in multiple select

### ISSUE THREAD

**Issue by gparonitti** [basvandenberg/ng-select#163]
```html
<div class="form-group required">
  <label>Supported languages</label>
  <ng-select [options]="locales"
             [multiple]="true"
             (selected)="langSelectedPushToForm($event)"
             (deselected)="langDeselectedPopFromForm($event)"
             placeholder="Choose the languages">
  </ng-select>
</div>
```
The above code produce a multiple select but no filter:
![administration_panel](https://cloud.githubusercontent.com/assets/11628507/25488927/a00be52e-2b68-11e7-8aba-257ec8c07724.png)

From the documentation/examples I thought it was possible: there is a point "No filter multiple select" which explains how to hide the filter on multiple select, so I derived that by default multiple selects have the filter. Is there something I am missing?

**Comment by gparonitti** [comment]
I proposed the following modification to solve this issue: #164

**Comment by basvandenberg** [comment]
Your screenshot shows a cursor before the 'Choose the languages' placeholder. This is the filter for the multi-select. Just start typing and the list will be filtered.

The multi-select filter is located inline after the last selected option. The single-select filter is located underneath the currently selected option (so that you can still see what the currently selected option is).
