### ISSUE TITLE
Issue with loading remote data

### ISSUE THREAD

**Issue by xocasdashdash** [basvandenberg/ng-select#169]
Hi!
I've had an issue using this component, the issue is the following:
1 - I load data on ngOnInit from a remote server
2 - I use this data to set the different options and to set the selected option
3 - It fails unless I wrap setting the value in a setTimeout(()=> this.selectedOptions = tempOption)

I've managed to reproduce the issue on this plunker:
https://plnkr.co/edit/v9xkQUqHnq3aKX632xgd

As you can see here the options1 options (the bottom select) are loaded on the constructor and the options0 options are loaded on the ngOnInit method, when it runs you can see how the bottom ng-select is working correctly but the top one isn't.

This is not happening when you use normal select on even the angular material select component so I'm guessing it's a bug

**Comment by basvandenberg** [comment]
If you change a component's input (such as the list of options), angular needs time to detect this. Then it will inform the component that an input has changed (it calls its ngOnChanges). 

If you select options right after you have set the list of options, the component has not yet been informed about this list of options, so it will not yet be able to select any of them. The setTimeout guarantees that the change detection is performed, so that the component knows about the options, and selecting the options will actually work.

Not nice, but also not really a bug in the select component I'd say. Nevertheless, it would be nice to improve this, and I would be open for suggestions.

**Comment by saithis** [comment]
Maybe allow the component to have a value that is not in the list, as long as the list is not set. As soon as the list gets set, check if the value is in the list and remove it, if it isn't.

**Comment by xocasdashdash** [comment]
@basvandenberg Yeah, that was my idea too. I've looked at how the md-select component from angular material works and they have two components md-select and md-options and the ngModel of md-select are the options that were added ([link](https://github.com/angular/material2/blob/master/src/lib/select/select.ts#L228)) so this problem doesn't show up.

@saithis I think what you're proposing is the solution I had to come up with, you would just be moving that logic into the component right? 

Maybe this is a good enough solution and it just needs to be documented, for me it basically was a happy idea

**Comment by wis-gss** [comment]
Hi everyone.
@basvandenberg , I faced with this problem when using WebSockets and want to suggest you implement some EventEmmiter which create callback when options had been changed (at least as a temporary solution).
What do you think about it? It's a dirty hack, but I think it's better than setTimeout

**Comment by basvandenberg** [comment]
I am looking into to this, but need a bit more time to test if my current solution does not affect any other functionality.  This solution would enable setting the value directly after updating the options without nesting it in a setTimeout.

**Comment by basvandenberg** [comment]
In the upcoming beta.6 release it will be possible to set a value while there is no list of options yet. This should solve the issue. No more need for the `setTimeout`, in fact you don't need to wait for the options to be loaded before setting the value.
