### ISSUE TITLE
"opened" Output-Event not working properly

### ISSUE THREAD

**Issue by MStoehr** [basvandenberg/ng-select#189]
The "opened"-Output Event almost always returns "null" (except on focus, i get false);
For me, the docs are not quite clear: Is this intended? 

Otherwise I'd like to request setting this to a two-way-binding attribute, so that one is able to hand over a variable which is set to true/false whenever the .isOpen-property changes.

**Comment by basvandenberg** [comment]
There are two output events: `opened` and `closed`, as specified in the [README](https://github.com/basvandenberg/ng-select#output-events). They both submit the value null, because there is not really a need to forward any data, the event speaks for itself, the drop down is opened. You can use these events to track in what state the drop down is:

```html
<ng-select
    [options]="yourOptions"
    (opened)="onOpened()"
    (closed)="onClosed()">
</ng-select>
``` 
```typescript
    // Somewhere in your component.
    private selectDropDownIsOpened: boolean = false;
    ...
    onOpened() {
        this.selectDropDownIsOpened = true;
    }
    onClosed() {
        this.selectDropDownIsOpened = false;
    }
```
