### ISSUE TITLE
In ng-select dropdown, on searching for a text, the listed items matching the search criteria having the searched text in bold, when clicked does not get the item selected.

### ISSUE THREAD

**Issue by chaisangam** [basvandenberg/ng-select#216]
In ng-select dropdown, on searching for a text, the listed items matching the search criteria having the searched text in bold, when clicked does not get the item selected. If you click anywhere else leaving the searched text in bold, it works fine. How to fix this?

**Comment by basvandenberg** [comment]
When filtering the list of options, the matching part of an option is **not** made bold in this component. I guess this is an issue for some other select component?

**Comment by tannenbaums** [comment]
I have the same exact issue. I'm using the latest version 5.0.9 (but this issue was there in previous versions as well). Here are the repro steps:
If I search for an item once, I hit enter and everything is fine. Now I'll move to something else then come back and search for it again, the item will now show up in bold (until now it was not in bold) and when I hit the enter key it stays on the current item I'm on. It will not select the searched item.

**Comment by tannenbaums** [comment]
Actually, I see that I only happens with one of our dropdown in which we use it for hierarchal data:

`<ng-select #childList id="childList" [(ngModel)]="Manager.selectedChildId" bindLabel="name" [required]="Manager.required" (open)="Manager.ChildListOpen(childList)" [clearable]="false" groupBy="parent" [dropdownPosition]="'bottom'">
    <ng-option [value]="-1" *ngIf="!Manager.hasOneEntityOnly">All Entities</ng-option>
    <ng-template ngFor let-entityParent [ngForOf]="Manager.childListData">
      <ng-option [disabled]="true" value="parent" *ngIf="!Manager.hasOneChildOnly && !Manager.hasOneParentOnly">--{{parent.name}}--</ng-option>
      <ng-option *ngFor="let child of parent.inverseParent" [value]="child.id">{{child.name}}</ng-option>
    </ng-template>
  </ng-select>`

**Comment by tannenbaums** [comment]
sorry you are right, this is not the one i'm using. sorry about that...
