### ISSUE TITLE
How to set default value using Reactive Form? 

### ISSUE THREAD

**Issue by bhushangahire** [basvandenberg/ng-select#250]
I am always getting `ERROR TypeError: Value must be a string or an array.` even when I am passing the value as a string.

**Comment by basvandenberg** [comment]
Have a look at [this](https://basvandenberg.github.io/ng-select#/examples/reactive-form) example. If you still have problems getting it to work, then please post your question (include some code, because now its impossible to see what you might have done wrong) on StackOverflow or something similar to get help. This is for reporting issues.
