### ISSUE TITLE
Allow using templates for complex item markup

### ISSUE THREAD

**Issue by tiagoroldao** [basvandenberg/ng-select#92]
For more complex usages of a the component, such as displaying list groups with item description, images, etc.

**Comment by daveriedstra** [comment]
As far as I can tell, the current option template solution, described in the documentation [here](https://basvandenberg.github.io/ng-select/examples/option-template), gives two possibilities for extra data related to an option, neither of which are ideal. Does anyone have a better way?

**option 1: extra properties on the option itself**
As long as the option implements `IOption` _(and we don't care too much about writing 100% perfect TypeScript)_ it can have other properties as well, which can be accessed in the template. The drawback is that when an option is selected, only its `IOption` values are used, so the template for the selected option doesn't have access to the extra properties.
```
public selectOptions: IOption[];
public dataOptions: OriginalType[];

// ...

ngOnInit() {
    this.selectOptions = this.dataOptions.map(o => {
            return {
                label: o.name,
                value: o.id,
                img: o.imgSrc
            } as IOption;
    });
}
```

**option 2: maintain two lists and perform a lookup in the template**
so that the component has 
```
public selectOptions: IOption[];
public dataOptions: OriginalType[];
public getImg(o: IOption): SafeResourceUrl { /* ... */ }
```
and the template uses it like so (roughly)
```
<ng-select [options]="selectOptions">
    <ng-template
        #optionTemplate
        let-option="option">
        <img [src]="getImg(option)" />
    </ng-template>
</ng-select>
```
This will work in the list as well as in the selected element, but will incur a performance hit as it has to filter the `OriginalType[]` list every change detection run.

**Comment by basvandenberg** [comment]
> As long as the option implements IOption (and we don't care too much about writing 100% perfect TypeScript) 

Your options do not have to implement the `IOption` interface explicitly, using the following `ngSelectList` will work just fine:

```ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent {
    ngSelectList = [
        {label: 'Hello', value: '0', finished: true},
        {label: 'Blaat', value: '1', finished: true},
        {label: 'Test', value: '2', finished: false},
        {label: 'Ladieda', value: '3', finished: false}
    ];
}
```
But all options will need to have a `label` and `value` attribute for the `ng-select` component to work. Those who want can import the `IOption` interface and have their options implement this interface explicitly.

> so the template for the selected option doesn't have access to the extra properties

What? Why? As the documentation states, you **can** use any of the attributes in your option object. The following template uses the `finished` property to add a smiley to all options for which the `finished` property is `true`.
```html
<ng-select [options]="ngSelectList">
    <ng-template
        #optionTemplate
        let-option="option">
        <span>{{option.label}}</span><span *ngIf="option.finished"> :)</span>
    </ng-template>
</ng-select>
```

**Comment by basvandenberg** [comment]
But there is a bug there... The `finished` property is used in the drop down options, but not for the selected option, I'll fix that. Thanks!

**Comment by daveriedstra** [comment]
>  but not for the selected option,
That's exactly what I meant. Sorry for the confusing write up and thanks for looking into it!
